version: "3.8"
services:
  stock_backend:
    image: registry.gitlab.com/gregorymark25/rbt_content_server
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - node-network

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - rbt_backend
    networks:
      - node-network

  stockplus:
    image: mysql:8.0.29
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5300:3306"
    volumes:
      - /usr/local/lib/rbt_content_server/rbt_sql_storage:/var/lib/mysql
    networks:
      - node-network

networks:
  node-network:
